<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.nsn.cumulocity.clients-java</groupId>
    <artifactId>microservice-dependencies</artifactId>
    <version>${revision}${changelist}</version>

    <name>Cumulocity :: Clients Java :: Microservice</name>
    <description>Microservice</description>
    <packaging>pom</packaging>

    <properties>
        <revision>2026.46.0</revision>
        <changelist></changelist>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>17</java.version>
        <nexus.url>http://localhost:8080</nexus.url>
        <nexus.basePath>/nexus/content/repositories</nexus.basePath>

        <cumulocity.clients.version>${project.version}</cumulocity.clients.version>
        <googleauth.version>1.1.1</googleauth.version>
        <rest-assured.version>6.0.1</rest-assured.version> <!-- no longer managed by Spring Boot 4.0; kept at the 3.5.x version -->
        <spring-boot.version>4.0.7</spring-boot.version>
        <spring-framework.version>7.0.8</spring-framework.version> <!-- bound with spring-boot.version -->
    </properties>

    <modules>
        <module>autoconfigure</module>
        <module>context</module>
        <module>api</module>
        <module>security</module>
        <module>properties</module>
        <module>subscription</module>
        <module>logging</module>
        <module>custom-decoders</module>
        <module>custom-encoders</module>
        <module>lpwan-custom-codec</module>
        <module>package</module>
        <module>monitoring</module>
        <module>settings</module>
    </modules>

    <organization>
        <name>(C) Cumulocity GmbH</name>
    </organization>

    <inceptionYear>2017</inceptionYear>

    <dependencyManagement>
        <dependencies>
            <!-- PLEASE add new dependencies ALPHABETICALLY -->

            <!-- BOM DEPENDENCIES START -->
            <dependency>
                <groupId>com.nsn.cumulocity.clients-java</groupId>
                <artifactId>clients-java</artifactId>
                <version>${cumulocity.clients.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- BOM DEPENDENCIES END -->

            <!-- PLEASE add new dependencies ALPHABETICALLY -->

            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-core</artifactId>
                <version>${spring-framework.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>commons-logging</groupId>
                        <artifactId>commons-logging</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <!-- COMPILE DEPENDENCIES START -->
            <dependency>
                <groupId>com.nsn.cumulocity.clients-java</groupId>
                <artifactId>microservice-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nsn.cumulocity.clients-java</groupId>
                <artifactId>microservice-context</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nsn.cumulocity.clients-java</groupId>
                <artifactId>microservice-logging</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nsn.cumulocity.clients-java</groupId>
                <artifactId>microservice-monitoring</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nsn.cumulocity.clients-java</groupId>
                <artifactId>microservice-platform-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nsn.cumulocity.clients-java</groupId>
                <artifactId>microservice-properties</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nsn.cumulocity.clients-java</groupId>
                <artifactId>microservice-security</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nsn.cumulocity.clients-java</groupId>
                <artifactId>microservice-settings</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.nsn.cumulocity.clients-java</groupId>
                <artifactId>microservice-subscription</artifactId>
                <version>${project.version}</version>
            </dependency>
            <!-- COMPILE DEPENDENCIES END -->

            <!-- PLEASE add new dependencies ALPHABETICALLY -->

            <!-- TEST DEPENDENCIES START -->
            <dependency>
                <groupId>io.rest-assured</groupId>
                <artifactId>rest-assured</artifactId>
                <version>${rest-assured.version}</version>
            </dependency>
            <dependency>
                <groupId>io.rest-assured</groupId>
                <artifactId>spring-mock-mvc</artifactId>
                <version>${rest-assured.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-test</artifactId>
                <version>${spring-boot.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.vaadin.external.google</groupId>
                        <artifactId>android-json</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <!-- TEST DEPENDENCIES END -->

            <!-- PLEASE add new dependencies ALPHABETICALLY -->
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>3.6.2</version>
                    <configuration>
                        <rules>
                            <requireMavenVersion>
                                <version>3.9</version>
                            </requireMavenVersion>
                            <requireJavaVersion>
                                <version>${java.version}</version>
                            </requireJavaVersion>
                            <dependencyConvergence />
                            <bannedDependencies>
                                <excludes><exclude>commons-logging:commons-logging</exclude></excludes>
                                <message>Dependency to commons-logging:commons-logging was replaced by org.slf4j:jcl-over-slf4j</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>javax.activation</exclude></excludes>
                                <message>Dependency to javax.activation was replaced by jakarta.activation</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>javax.annotation</exclude></excludes>
                                <message>Dependency to javax.annotation was replaced by jakarta.annotation</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>javax.el</exclude></excludes>
                                <message>Dependency to javax.el was replaced by jakarta.el</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>javax.mail</exclude></excludes>
                                <message>Dependency to javax.mail was replaced by jakarta.mail</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>javax.servlet</exclude></excludes>
                                <message>Dependency to javax.servlet was replaced by jakarta.servlet</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>javax.validation</exclude></excludes>
                                <message>Dependency to javax.validation was replaced by jakarta.validation</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>javax.ws.rs</exclude></excludes>
                                <message>Dependency to javax.ws.rs was replaced by jakarta.ws.rs</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>javax.xml.bind</exclude></excludes>
                                <message>Dependency to javax.xml.bind was replaced by jakarta.xml.bind</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>org.bouncycastle:*-jdk15on</exclude></excludes>
                                <message>Dependency to org.bouncycastle:*-jdk15on was replaced by org.bouncycastle:*-jdk18on</message>
                            </bannedDependencies>
                        </rules>
                    </configuration>
                    <executions>
                        <execution>
                            <id>enforce-rules</id>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>flatten-maven-plugin</artifactId>
                    <version>1.7.3</version>
                    <configuration>
                        <updatePomFile>true</updatePomFile>
                        <flattenMode>resolveCiFriendliesOnly</flattenMode>
                    </configuration>
                    <executions>
                        <execution>
                            <id>flatten</id>
                            <phase>process-resources</phase>
                            <goals>
                                <goal>flatten</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>flatten.clean</id>
                            <phase>clean</phase>
                            <goals>
                                <goal>clean</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>build-helper-maven-plugin</artifactId>
                    <version>3.6.1</version>
                    <executions>
                        <execution>
                            <id>should-skip-remote-resources-process</id>
                            <phase>initialize</phase>
                            <goals>
                                <goal>bsh-property</goal>
                            </goals>
                            <configuration>
                                <source>skipRemoteResourcesProcess = "jar" != "${project.packaging}"</source>
                                <properties>
                                    <property>skipRemoteResourcesProcess</property>
                                </properties>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <version>3.10.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-remote-resources-plugin</artifactId>
                    <version>3.3.0</version>
                    <configuration>
                        <properties>
                            <thirdPartiesLink>https://third-parties.c8y.io/sboms/java-sdk/third_parties_java-sdk_${revision}${changelist}.html</thirdPartiesLink>
                        </properties>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>process</goal>
                            </goals>
                            <configuration>
                                <skip>${skipRemoteResourcesProcess}</skip>
                                <resourceBundles>
                                    <resourceBundle>com.nsn.cumulocity.clients-java:resource-bundle:${revision}${changelist}</resourceBundle>
                                </resourceBundles>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.15.0</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                        <parameters>true</parameters>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.5.5</version>
                    <configuration>
                        <argLine>-Xms256m -Xmx512m -XX:MetaspaceSize=96m -XX:MaxMetaspaceSize=128m -Duser.timezone=GMT</argLine>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>aspectj-maven-plugin</artifactId>
                    <version>1.16.0</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                        <complianceLevel>${java.version}</complianceLevel>
                        <showWeaveInfo>true</showWeaveInfo>
                        <verbose>true</verbose>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring-boot.version}</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>repackage</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.5.0</version>
                    <configuration>
                        <archive>
                            <manifestEntries>
                                <Dependencies>https://third-parties.c8y.io/sboms/java-sdk/third_parties_java-sdk_${project.version}.html</Dependencies>
                            </manifestEntries>
                        </archive>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>com.nsn.cumulocity.clients-java</groupId>
                    <artifactId>microservice-package-maven-plugin</artifactId>
                    <version>${project.version}</version>
                    <executions>
                        <execution>
                            <id>package</id>
                            <phase>package</phase>
                            <goals>
                                <goal>package</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>push</id>
                            <phase>package</phase>
                            <goals>
                                <goal>push</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>microservice-deploy</id>
                            <phase>package</phase>
                            <goals>
                                <goal>microservice-deploy</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <!-- Javadoc -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>3.12.0</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>aggregate-jar</goal>
                            </goals>
                        </execution>
                    </executions>
                        <configuration>
                            <doctitle>Cumulocity Microservice SDK</doctitle>
                            <windowtitle>Cumulocity Microservice SDK</windowtitle>
                            <overview>${project.basedir}/javadoc/overview.html</overview>
                            <source>17</source>
                            <detectOfflineLinks>false</detectOfflineLinks> <!-- https://github.com/apache/maven-javadoc-plugin/issues/1258 -->
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-remote-resources-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <distributionManagement>
        <snapshotRepository>
            <id>snapshot</id>
            <url>${nexus.url}${nexus.basePath}/snapshots</url>
        </snapshotRepository>
        <repository>
            <id>release</id>
            <url>${nexus.url}${nexus.basePath}/releases</url>
        </repository>
    </distributionManagement>

    <profiles>
        <profile>
            <id>ci</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                        <version>0.8.14</version>
                        <configuration>
                            <destFile>${project.basedir}/../target/jacoco.exec</destFile>
                            <append>true</append>
                        </configuration>
                        <executions>
                            <execution>
                                <id>default-prepare-agent</id>
                                <goals>
                                    <goal>prepare-agent</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>default-report</id>
                                <phase>prepare-package</phase>
                                <goals>
                                    <goal>report</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>pre-merge</id>
            <distributionManagement>
                <snapshotRepository>
                    <id>pre-merge</id>
                    <url>${nexus.url}${nexus.basePath}/pre-merge</url>
                </snapshotRepository>
                <repository>
                    <id>pre-merge</id>
                    <url>${nexus.url}${nexus.basePath}/pre-merge</url>
                </repository>
            </distributionManagement>
        </profile>
    </profiles>

</project>
