package com.cumulocity.email.client;

import com.cumulocity.model.email.Email;

/**
 * Email API is going to be removed completely in the future
 */
@Deprecated
public interface EmailApi {

    /**
     * Sends an email from the platform. The sender does not have to be set, since it will be generated by the platform
     *
     * @param email an email to be sent
     * @return an HTTP status of a request, 200 OK in case if an email was sent successfully
     */
    int sendEmail(Email email);
}
