pipeline {
    agent {
        kubernetes {
            inheritFrom 'jdk11'
            defaultContainer 'default'
        }
    }
    options {
        quietPeriod(15)
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timeout(time: 20, unit: 'MINUTES')
    }
    triggers {
        upstream(upstreamProjects: "/${currentBuild.fullProjectName.replaceFirst('cumulocity-clients-java', 'cumulocity-core')}",
            threshold: hudson.model.Result.SUCCESS)
    }
    environment {
        MVN_SETTINGS = credentials('maven-settings')
    }
    stages {
        stage('build') {
            when {
                anyOf {
                    branch 'develop'
                    branch 'release/*'
                }
            }
            stages {
                stage('sdk checkout') {
                    steps {
                        dir('cumulocity-sdk') {
                            checkout resolveScm(
                                source: [id: '_', $class: 'GitSCMSource',
                                         remote: 'https://github.softwareag.com/IOTA/cumulocity-sdk',
                                         credentialsId: 'Cumulocity-Jenkins',
                                         traits: [ gitBranchDiscovery() ]],
                                targets: [env.BRANCH_NAME, env.CHANGE_BRANCH, env.CHANGE_TARGET])
                        }
                    }
                }
                stage('verify & publish') {
                    steps {
                        sh ".jenkins/scripts/mvn.sh deploy"
                    }
                    post {
                        always {
                            junit(testResults: '**/TEST-*.xml', keepLongStdio: true, allowEmptyResults: true)
                        }
                    }
                }
            }
        }
    }
}
