<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>c8y.agents.lpwan.backend</groupId>
    <artifactId>lpwan-backend</artifactId>
    <name>Cumulocity :: LPWAN Backend</name>
    <packaging>jar</packaging>
    <version>${revision}${changelist}</version>

    <properties>
        <revision>2026.46.0</revision>
        <changelist></changelist>

        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <nexus.url>http://localhost:8080</nexus.url>
        <nexus.basePath>/nexus/content/repositories</nexus.basePath>

        <commons-text.version>1.15.0</commons-text.version>
    </properties>

    <organization>
        <name>(C) Cumulocity GmbH</name>
    </organization>

    <inceptionYear>2021</inceptionYear>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.nsn.cumulocity.clients-java</groupId>
                <artifactId>microservice-dependencies</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-text</artifactId>
            <version>${commons-text.version}</version>
        </dependency>
        <dependency>
            <groupId>com.nsn.cumulocity.clients-java</groupId>
            <artifactId>lpwan-custom-codec</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <artifactId>junit-vintage-engine</artifactId>
                    <groupId>org.junit.vintage</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.nsn.cumulocity.clients-java</groupId>
            <artifactId>java-client</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.nsn.cumulocity.clients-java</groupId>
            <artifactId>microservice-autoconfigure</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-resolver-dns-native-macos</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-jackson</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-jackson2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.nsn.cumulocity.model</groupId>
            <artifactId>device-capability-model</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-csv</artifactId>
            <version>1.13.0</version>
        </dependency>
        <dependency>
            <groupId>org.skyscreamer</groupId>
            <artifactId>jsonassert</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>


    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>3.6.2</version>
                    <configuration>
                        <rules>
                            <requireMavenVersion>
                                <version>3.9</version>
                            </requireMavenVersion>
                            <requireJavaVersion>
                                <version>${java.version}</version>
                            </requireJavaVersion>
                            <dependencyConvergence />
                            <bannedDependencies>
                                <excludes><exclude>commons-logging:commons-logging</exclude></excludes>
                                <message>Dependency to commons-logging:commons-logging was replaced by org.slf4j:jcl-over-slf4j</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>javax.activation</exclude></excludes>
                                <message>Dependency to javax.activation was replaced by jakarta.activation</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>javax.annotation</exclude></excludes>
                                <message>Dependency to javax.annotation was replaced by jakarta.annotation</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>javax.el</exclude></excludes>
                                <message>Dependency to javax.el was replaced by jakarta.el</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>javax.mail</exclude></excludes>
                                <message>Dependency to javax.mail was replaced by jakarta.mail</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>javax.servlet</exclude></excludes>
                                <message>Dependency to javax.servlet was replaced by jakarta.servlet</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>javax.validation</exclude></excludes>
                                <message>Dependency to javax.validation was replaced by jakarta.validation</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>javax.ws.rs</exclude></excludes>
                                <message>Dependency to javax.ws.rs was replaced by jakarta.ws.rs</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>javax.xml.bind</exclude></excludes>
                                <message>Dependency to javax.xml.bind was replaced by jakarta.xml.bind</message>
                            </bannedDependencies>
                            <bannedDependencies>
                                <excludes><exclude>org.bouncycastle:*-jdk15on</exclude></excludes>
                                <message>Dependency to org.bouncycastle:*-jdk15on was replaced by org.bouncycastle:*-jdk18on</message>
                            </bannedDependencies>
                        </rules>
                    </configuration>
                    <executions>
                        <execution>
                            <id>enforce-rules</id>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>flatten-maven-plugin</artifactId>
                    <version>1.7.3</version>
                    <configuration>
                        <updatePomFile>true</updatePomFile>
                        <flattenMode>resolveCiFriendliesOnly</flattenMode>
                    </configuration>
                    <executions>
                        <execution>
                            <id>flatten</id>
                            <phase>process-resources</phase>
                            <goals>
                                <goal>flatten</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>flatten.clean</id>
                            <phase>clean</phase>
                            <goals>
                                <goal>clean</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-remote-resources-plugin</artifactId>
                    <version>3.3.0</version>
                    <configuration>
                        <properties>
                            <thirdPartiesLink>https://third-parties.c8y.io/sboms/java-sdk/third_parties_java-sdk_${revision}${changelist}.html</thirdPartiesLink>
                        </properties>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>process</goal>
                            </goals>
                            <configuration>
                                <resourceBundles>
                                    <resourceBundle>com.nsn.cumulocity.clients-java:resource-bundle:${revision}${changelist}</resourceBundle>
                                </resourceBundles>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.16.0</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                        <parameters>true</parameters>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.5.5</version>
                    <configuration>
                        <argLine>-Xms256m -Xmx512m -XX:MetaspaceSize=96m -XX:MaxMetaspaceSize=128m</argLine>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.5.0</version>
                    <configuration>
                        <archive>
                            <manifestEntries>
                                <Dependencies>https://third-parties.c8y.io/sboms/java-sdk/third_parties_java-sdk_${project.version}.html</Dependencies>
                            </manifestEntries>
                        </archive>
                    </configuration>
                </plugin>
                <!-- Javadoc -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>3.12.0</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>aggregate-jar</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <doctitle>Cumulocity lpwan backend shared component</doctitle>
                        <windowtitle>Cumulocity lpwan backend shared component</windowtitle>
                        <overview>${project.basedir}/javadoc/overview.html</overview>
                        <source>${java.version}</source>
                        <detectOfflineLinks>false</detectOfflineLinks> <!-- https://github.com/apache/maven-javadoc-plugin/issues/1258 -->
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-remote-resources-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <distributionManagement>
        <snapshotRepository>
            <id>snapshot</id>
            <url>${nexus.url}${nexus.basePath}/snapshots</url>
        </snapshotRepository>
        <repository>
            <id>release</id>
            <url>${nexus.url}${nexus.basePath}/releases</url>
        </repository>
    </distributionManagement>

    <profiles>
        <profile>
            <id>pre-merge</id>
            <distributionManagement>
                <snapshotRepository>
                    <id>pre-merge</id>
                    <url>${nexus.url}${nexus.basePath}/pre-merge</url>
                </snapshotRepository>
                <repository>
                    <id>pre-merge</id>
                    <url>${nexus.url}${nexus.basePath}/pre-merge</url>
                </repository>
            </distributionManagement>
        </profile>
    </profiles>
</project>
